### ISSUE TITLE
Hash Calculator

### ISSUE THREAD

**Issue by Thunderosa** [M5M400/supportxmr-gui#2]
Someone suggested this on IRC, could be integrated into the miners chart.

**Comment by M5M400** [comment]
you mean like xmr/day based on avg. hashrate?

**Comment by Thunderosa** [comment]
Yeah, exactly. I think I can work in something simple into the miner's main graph without too much hassle. We have some room there.

**Comment by kic0** [comment]
I like the idea, tho it has been disconsidered in the past because it tends to lead new miners in mistake and all the "but the site said I would get X and only got Y" kind of complaints ... just my take on it ...

**Comment by M5M400** [comment]
It's also dependent on external APIs
