### ISSUE TITLE
API Help

### ISSUE THREAD

**Issue by optikkore** [M5M400/supportxmr-gui#21]
Hey, not a bug but more of a help, because I'm floundering trying to reverse engineer the code to figure out how you calculated some stats from the api data. I am trying to use rest-api in HomeAssistant to make a little dashboard to show me my stats like i did when I was at monerohash. I have gotten the basic readable stuff from /stats and a count of pending blocks but to get the hashrate from the /chart/hashrate but I can't make heads or tails of how to compute it. is there a secrete api that gives a bunch of readable stats for the address or would you mind sharing the formula or a feature request maybe of an api call that shoots out the json of all readable stats you would be looking at on the website dashboard. Thanks for even taking the time to read this.

**Comment by Thunderosa** [comment]
Hi optikkore, you're right that it's not very clear what's going on here. This does use an API, for example, with the NetHash, the TimerUpdateData() function is calling the api() function and storing the values in $D. 

NetHash is an estimated value calculated as (Difficulty / 120). 120 is the target blocktime in seconds, Monero's two minute block target. So in the code you'll just see things getting multiplied or divided by 120 to switch between Difficulty and NetHash.

**Comment by optikkore** [comment]
im really stupid it was directly in /api/miner/$address/stats/$identifier with the key hash, sorry
