### ISSUE TITLE
Progress of mining not reflected on the browser

### ISSUE THREAD

**Issue by DMerckz** [M5M400/supportxmr-gui#22]
The browser monitor of mining stop updating and indicate that miner is not active (Please see below).
![image](https://user-images.githubusercontent.com/90919230/133804429-fdda0a27-53ed-4ab9-9bdc-5c841e7a68f0.png)

While all along the the miner continues work as shown below
![image](https://user-images.githubusercontent.com/90919230/133804200-289d2a04-c3ac-4141-bf9d-8ca8d84c9aae.png)

**Comment by Plovri** [comment]
Same here

**Comment by M5M400** [comment]
this is not an issue related to the frontend. it's an issue related to xmrfast.com pool. it appears their node is stuck for the past two days.
