### ISSUE TITLE
function XMRHashTruncate()

### ISSUE THREAD

**Issue by miziel** [M5M400/supportxmr-gui#9]
There are wrong links created in Payments view and in the list of miner's transactions on Home page.
Not sure, but I think the culprit is the function, which uses xmrchain.net/block/ url, which is fine for block listing, but for transactions it should be xmrchain.net/tx/

**Comment by Thunderosa** [comment]
Thanks for bringing this up. The new version doesn't display the transaction hash on the pool payments page, but this bug also existed for the miner payment interface. It's been fixed. Thanks!
